openapi: "3.0.0"
info:
  version: 1.0.0
  title: Garden Project API
  description: _Plan and track your garden_
servers:
- url: http://localhost:8080
  description: local development environment
paths:
  /api/v1/roles:
    get:
      description: get all RBAC roles in the system
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRolesResponse'
components:
  schemas:
    ListRolesResponse:
      type: array
      items:
        type: object
        additionalProperties:
          $ref: '#/components/schemas/RBACRole'
    RBACRole:
      type: 'object'
      properties:
        id: {"type": "string"}
        name: {"type": "string"}